# Site settings
title: Jxqt Blog
SEOTitle: 今星期天的博客 | Jxqt Blog
# header-img: 
email: zjkgf@163.com
description: "关于程序与设计、黑客与画家 | 黄玄，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 @Hux黄玄 的个人博客，与你一起发现更大的世界。"
keyword: "今星期天, 星期天, Jxqt, 周天, 礼拜天, @周日, 今星期天的博客, jxqt Blog, 博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https://jxqt.github.io"              # your host, for absolute URL
# baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false


Build settings:      3
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
# highlighter: rouge
# permalink: pretty
paginate: 10
# 下面👇不包括中括号里的内容
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
# 👇 anchor.js 是简单且有用的 jQuery 插件，为所有本地链接提供一个平滑的动画，然后跳转到页面的任意一个元素
anchorjs: false                          
# if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
# timezone: CN  





# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
# gems: [jekyll-paginate]
# 下面行👇为分页插件
plugins: [jekyll-paginate]


# 下面👇为轻量级编辑语言设置
# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                           
# use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
# disqus_username: hux

# Netease settings
# netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
# sidebar-about-description: "For the next quantum leap<br>离开世界之前，一切都是过程"
# sidebar-avatar: /img/avatar-hux-ny.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# 👇 漸進式網路應用程式是一種普通網頁或網站架構起來的網路應用程式，但它可以以傳統應用程式或原生行動應用程式形式展示給使用者。這種應用程式形態視圖將目前最為現代化的瀏覽器提供的功能與行動裝置的體驗優勢相結合。
# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
# MathJax是一個跨瀏覽器的JavaScript 程式庫，它使用MathML、LaTeX和ASCIIMathML標記在Web瀏覽器中顯示數學符號。MathJax是在Apache授權條款下作為開源軟體發布的。
page-mathjax: false



# Friends
friends: [
    {
      title: "薰衣草，洋",
      href: "https://v.kuaishou.com/zHs3qD"
    },{
      title: "wpys168",
      href: "http://sj.ysupan.com/zjkgf"
    },{
        title: "k1314",
        href: "https://v.kuaishou.com/xgauhm"
    },{
        title: "琴妹427774279",
        href: "https://v.kuaishou.com/z1HiAI"
    },{
        title: "韩女团ba",
        href: "https://v.kuaishou.com/Bj0WcX"
    },{
        title: "微信ajtdjt",
        href: "https://v.kuaishou.com/zXmkKl"
    },{
        title: "南方泵业",
        href: "https://ksirq.github.io/"
    },{
        title: "平邑防水",
        href: "https://rsxj.github.io/"
    },{
        title: "GitHub",
        href: "https://www.github.com/"
    },{
        title: "Jxqt",
        href: "https://jxqt.github.io/"
    },{
        title: "google mail",
        href: "https://mail.google.com"
    },{
        title: "git写博",
        href: "https://github.com/jxqt/jxqt.github.io/tree/master/_posts"
    } ,{
        title: "梁山立鸿二手设备买卖",
        href: "https://v.kuaishou.com/zRZMUU"
    }


]

theme: jekyll-theme-cayman
